#!/system/bin/sh

/system/bin/mount -o rw,fmask=000,dmask=000,uid=1023,gid=1023,nosuid -t vfat /dev/block/mmcblk0p1 /storage/sdcard1
/system/bin/mount -o rw,fmask=000,dmask=000,uid=1023,gid=1023,nosuid -t vfat /dev/block/mmcblk1p1 /storage/sdcard2
